rules:
  unpinned-uses:
    config:
      # TODO: allow only bitcart/*
      policies:
        "*": ref-pin
  secrets-outside-env:
    config:
      allow:
        - CODECOV_TOKEN # coverage uploads is safe
  unpinned-images: # TODO: remove when enabling pinning
    ignore:
      - ci.yml
