"""Store improvements

Revision ID: 0942568d6ea6
Revises: 88efda9b7d53
Create Date: 2019-12-14 18:30:50.411161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0942568d6ea6'
down_revision = '88efda9b7d53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('buyer_email', sa.String(length=10000)))
    op.add_column('products', sa.Column('download_url', sa.String(length=100000)))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'download_url')
    op.drop_column('invoices', 'buyer_email')
    # ### end Alembic commands ###
