"""Add store theme settings

Revision ID: 73d794ea10e2
Revises: e627af4b2a1c
Create Date: 2021-11-20 23:54:22.931026

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "73d794ea10e2"
down_revision: str | None = "e627af4b2a1c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("stores", sa.Column("theme_settings", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stores", "theme_settings")
    # ### end Alembic commands ###
