"""Add tx hashes to invoices

Revision ID: e037b5354fbf
Revises: be1f56ed9798
Create Date: 2022-11-06 20:40:02.929345

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e037b5354fbf"
down_revision: str | None = "c471d1bec577"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("invoices", sa.Column("tx_hashes", postgresql.ARRAY(sa.Text()), nullable=True, server_default="{}"))
    op.alter_column("invoices", "tx_hashes", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("invoices", "tx_hashes")
    # ### end Alembic commands ###
