"""Add email verification

Revision ID: 12f53bb6513c
Revises: 7d87040b9f50
Create Date: 2023-01-20 02:27:02.128776

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "12f53bb6513c"
down_revision = "7d87040b9f50"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("is_verified", sa.Boolean(), nullable=True, server_default="false"))
    op.add_column("users", sa.Column("is_enabled", sa.Boolean(), nullable=True, server_default="true"))
    op.alter_column("users", "is_verified", server_default=None)
    op.alter_column("users", "is_enabled", server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_enabled")
    op.drop_column("users", "is_verified")
    # ### end Alembic commands ###
