"""Store invoice paid date

Revision ID: 7a7d61641dd2
Revises: 2a33595c8b9d
Create Date: 2023-05-14 17:41:20.586487

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7a7d61641dd2"
down_revision: str | None = "2a33595c8b9d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("invoices", sa.Column("paid_date", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("invoices", "paid_date")
    # ### end Alembic commands ###
