"""Add plugin data

Revision ID: 3801b9cf3278
Revises: d143acc929ee
Create Date: 2022-12-18 21:40:23.649600

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "3801b9cf3278"
down_revision = "d143acc929ee"
branch_labels = None
depends_on = None


def add_json_field(table_name, column_name):
    op.add_column(table_name, sa.Column(column_name, sa.JSON(), nullable=True, server_default="{}"))
    op.alter_column(table_name, column_name, server_default=None)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    add_json_field("discounts", "plugins_data")
    add_json_field("invoices", "plugins_data")
    add_json_field("notifications", "plugins_data")
    add_json_field("paymentmethods", "plugins_data")
    add_json_field("payouts", "plugins_data")
    add_json_field("products", "plugins_data")
    add_json_field("stores", "plugins_data")
    add_json_field("templates", "plugins_data")
    add_json_field("tokens", "plugins_data")
    add_json_field("users", "plugins_data")
    add_json_field("wallets", "plugins_data")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("wallets", "plugins_data")
    op.drop_column("users", "plugins_data")
    op.drop_column("tokens", "plugins_data")
    op.drop_column("templates", "plugins_data")
    op.drop_column("stores", "plugins_data")
    op.drop_column("products", "plugins_data")
    op.drop_column("payouts", "plugins_data")
    op.drop_column("paymentmethods", "plugins_data")
    op.drop_column("notifications", "plugins_data")
    op.drop_column("invoices", "plugins_data")
    op.drop_column("discounts", "plugins_data")
    # ### end Alembic commands ###
