"""Add sso_type for users

Revision ID: 3a4cfc3d8819
Revises: 91e2cdaa49b5
Create Date: 2024-07-09 01:15:12.220704

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "3a4cfc3d8819"
down_revision = "91e2cdaa49b5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("currencies")
    op.add_column("users", sa.Column("sso_type", sa.Text(), nullable=True))
    op.execute("UPDATE users SET sso_type='password'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "sso_type")
    op.create_table(
        "currencies",
        sa.Column("symbol", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("count", sa.BIGINT(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
