"""Add user settings field

Revision ID: 3cfad1e70305
Revises: 3214530ea234
Create Date: 2021-06-06 21:54:16.470985

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "3cfad1e70305"
down_revision = "3214530ea234"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("settings", sa.JSON(), nullable=True, server_default="{}"))
    op.alter_column("users", "settings", server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "settings")
    # ### end Alembic commands ###
