"""Add store theme settings

Revision ID: 73d794ea10e2
Revises: e627af4b2a1c
Create Date: 2021-11-20 23:54:22.931026

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "73d794ea10e2"
down_revision = "e627af4b2a1c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("stores", sa.Column("theme_settings", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stores", "theme_settings")
    # ### end Alembic commands ###
