"""Store invoice paid date

Revision ID: 7a7d61641dd2
Revises: 2a33595c8b9d
Create Date: 2023-05-14 17:41:20.586487

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "7a7d61641dd2"
down_revision = "2a33595c8b9d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("invoices", sa.Column("paid_date", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("invoices", "paid_date")
    # ### end Alembic commands ###
