"""Make max str size bigger

Revision ID: 88efda9b7d53
Revises: 86bd32a3d5e9
Create Date: 2019-12-02 20:50:16.092540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88efda9b7d53'
down_revision = '86bd32a3d5e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoices', 'bitcoin_address',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=10000),
               existing_nullable=False)
    op.alter_column('invoices', 'bitcoin_url',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=10000),
               existing_nullable=False)
    op.alter_column('products', 'image',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=1000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'image',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('invoices', 'bitcoin_url',
               existing_type=sa.String(length=10000),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('invoices', 'bitcoin_address',
               existing_type=sa.String(length=10000),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
