"""Add SSO support

Revision ID: 8b2243e36a69
Revises: c8dc03c2cf76
Create Date: 2024-08-17 19:34:35.729094

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "8b2243e36a69"
down_revision = "c8dc03c2cf76"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("sso_type", sa.Text(), nullable=True))
    op.execute("UPDATE users SET sso_type='password'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "sso_type")
    # ### end Alembic commands ###
