"""Add recommended fee

Revision ID: 927a773be59d
Revises: d8515a8b706e
Create Date: 2021-01-22 19:48:25.437634

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "927a773be59d"
down_revision = "d8515a8b706e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "paymentmethods", sa.Column("recommended_fee", sa.Numeric(precision=16, scale=8), nullable=False, server_default="0")
    )
    op.alter_column("paymentmethods", "recommended_fee", server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("paymentmethods", "recommended_fee")
    # ### end Alembic commands ###
