"""add paid_currency to invoice

Revision ID: a27789cb7b2a
Revises: d47757e34b68
Create Date: 2020-09-12 00:07:55.231565

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "a27789cb7b2a"
down_revision = "d47757e34b68"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("invoices", sa.Column("paid_currency", sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("invoices", "paid_currency")
    # ### end Alembic commands ###
