"""Add ERC-20 tokens support

Revision ID: cecaf4545eb5
Revises: 69b52fb159ed
Create Date: 2022-03-20 17:25:23.147538

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "cecaf4545eb5"
down_revision = "69b52fb159ed"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("invoices", sa.Column("paid_contract", sa.Text(), nullable=True))
    op.add_column("paymentmethods", sa.Column("contracts", postgresql.ARRAY(sa.Text()), nullable=True, server_default="{}"))
    op.alter_column("paymentmethods", "contracts", server_default=None)
    op.add_column("wallets", sa.Column("contracts", postgresql.ARRAY(sa.Text()), nullable=True, server_default="{}"))
    op.alter_column("wallets", "contracts", server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("wallets", "contracts")
    op.drop_column("paymentmethods", "contracts")
    op.drop_column("invoices", "paid_contract")
    # ### end Alembic commands ###
