"""Add tx hashes to invoices

Revision ID: e037b5354fbf
Revises: be1f56ed9798
Create Date: 2022-11-06 20:40:02.929345

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "e037b5354fbf"
down_revision = "c471d1bec577"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("invoices", sa.Column("tx_hashes", postgresql.ARRAY(sa.Text()), nullable=True, server_default="{}"))
    op.alter_column("invoices", "tx_hashes", server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("invoices", "tx_hashes")
    # ### end Alembic commands ###
