"""Add wallets labels

Revision ID: e627af4b2a1c
Revises: 3cfad1e70305
Create Date: 2021-08-01 12:23:17.297194

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "e627af4b2a1c"
down_revision = "3cfad1e70305"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("wallets", sa.Column("label", sa.Text(), nullable=True))
    op.add_column("paymentmethods", sa.Column("label", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("wallets", "label")
    op.drop_column("paymentmethods", "label")
    # ### end Alembic commands ###
