"""Support underpaid invoices

Revision ID: efe99ea3b809
Revises: 7208e2a9a8e8
Create Date: 2021-01-21 23:00:01.119398

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "efe99ea3b809"
down_revision = "7208e2a9a8e8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("stores", sa.Column("underpaid_percentage", sa.Integer(), nullable=True, server_default="0"))
    op.alter_column("stores", "underpaid_percentage", server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stores", "underpaid_percentage")
    # ### end Alembic commands ###
