"""Fix html templates rendering

Revision ID: 5bf0a0845afb
Revises: e027e56adb58
Create Date: 2021-01-03 21:45:14.779772

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.sql import expression

# revision identifiers, used by Alembic.
revision: str = "5bf0a0845afb"
down_revision: str | None = "e027e56adb58"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("stores", sa.Column("use_html_templates", sa.Boolean(), nullable=True, server_default=expression.false()))
    op.alter_column("stores", "use_html_templates", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stores", "use_html_templates")
    # ### end Alembic commands ###
