"""Add store plugin settings

Revision ID: 850bd53dff02
Revises: 58f6fcd5af80
Create Date: 2022-05-01 15:11:56.127624

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "850bd53dff02"
down_revision: str | None = "58f6fcd5af80"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("stores", sa.Column("plugin_settings", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stores", "plugin_settings")
    # ### end Alembic commands ###
