"""Store wallet_ids with invoices

Revision ID: 704cd14b069a
Revises: 389288575d54
Create Date: 2025-10-03 01:53:06.441555

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "704cd14b069a"
down_revision = "389288575d54"
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("invoices", sa.Column("payment_methods", postgresql.ARRAY(sa.Text()), nullable=True))
    op.execute(
        "UPDATE invoices SET payment_methods = ARRAY(SELECT DISTINCT wallet_id FROM walletsxstores"
        " WHERE store_id = invoices.store_id)"
    )
    op.execute("COMMIT")
    op.alter_column("invoices", "payment_methods", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("invoices", "payment_methods")
    # ### end Alembic commands ###
