"""add wallet.transaction_speed

Revision ID: 898eb02ada93
Revises: 704cd14b069a
Create Date: 2025-10-24 18:10:29.447230

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "898eb02ada93"
down_revision = "704cd14b069a"
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("wallets", sa.Column("transaction_speed", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("wallets", "transaction_speed")
    # ### end Alembic commands ###
