"""Add per-wallet transaction speed

Revision ID: ce5bc44a5e3a
Revises: ff416380db04
Create Date: 2025-08-15 14:37:34.338029

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ce5bc44a5e3a"
down_revision: str | None = "ff416380db04"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("wallets", sa.Column("transaction_speed", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("wallets", "transaction_speed")
    # ### end Alembic commands ###
