name: Run in background

description: "Run a command in the background and output its logs in the post step."

inputs:
  run:
    description: "Command to run in the background."
    required: true
  key:
    description: "Unique key to identify this background process (used for log file names and state)."
    required: false
    default: POST

runs:
  using: composite
  steps:
    - uses: ./.github/actions/with-post-step
      with:
        key: ${{ inputs.key }}
        main: |
          bash --noprofile --norc -eo pipefail -c '
            BGDIR="${RUNNER_TEMP}/run-in-background"
            mkdir -p "$BGDIR"

            (${{ inputs.run }}) > "$BGDIR/${{ inputs.key }}.out" 2> "$BGDIR/${{ inputs.key }}.err" &
            disown
          '
        post: |
          BGDIR="${RUNNER_TEMP}/run-in-background"
          if [ -f "$BGDIR/${{ inputs.key }}.out" ]; then
            echo "::group::stdout"
            cat "$BGDIR/${{ inputs.key }}.out"
            echo "::endgroup::"
          fi
          if [ -f "$BGDIR/${{ inputs.key }}.err" ]; then
            echo "::group::stderr"
            cat "$BGDIR/${{ inputs.key }}.err"
            echo "::endgroup::"
          fi
