"""add user id

Revision ID: 30238e9d0bd2
Revises: 32974039eb89
Create Date: 2022-12-18 19:54:54.103016

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "30238e9d0bd2"
down_revision = "32974039eb89"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("plugin_testapi_reviews", sa.Column("user_id", sa.Text(), nullable=True))
    op.create_foreign_key(
        op.f("plugin_testapi_reviews_user_id_users_fkey"),
        "plugin_testapi_reviews",
        "users",
        ["user_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("plugin_testapi_reviews_user_id_users_fkey"), "plugin_testapi_reviews", type_="foreignkey")
    op.drop_column("plugin_testapi_reviews", "user_id")
    # ### end Alembic commands ###
