"""add metadata

Revision ID: 8bd5a33d909a
Revises: 30238e9d0bd2
Create Date: 2022-12-18 23:43:12.011692

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "8bd5a33d909a"
down_revision = "30238e9d0bd2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("plugin_testapi_reviews", sa.Column("metadata", sa.JSON(), nullable=True, server_default="{}"))
    op.alter_column("plugin_testapi_reviews", "metadata", server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("plugin_testapi_reviews", "metadata")
    # ### end Alembic commands ###
