# Generated by Django 2.1.7 on 2019-02-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('can_delete', models.IntegerField()),
                ('name', models.CharField(max_length=1000)),
                ('website', models.CharField(max_length=1000)),
                ('can_invoice', models.BooleanField(default=False)),
                ('xpub', models.CharField(max_length=1000)),
                ('invoice_expire', models.IntegerField(default=15)),
                ('fee_mode', models.IntegerField(choices=[(1, '... only if the customer makes more than one payment for the invoice'), (2, 'Always'), (3, 'Never')], default=1)),
                ('payment_tolerance', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'stores',
                'managed': True,
            },
        ),
    ]
