# Generated by Django 2.2.1 on 2019-05-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='email_host',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='store',
            name='email_password',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='store',
            name='email_port',
            field=models.IntegerField(blank=True, default=25),
        ),
        migrations.AddField(
            model_name='store',
            name='email_use_ssl',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='store',
            name='email_user',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
