# Generated by Django 2.1.7 on 2019-02-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='website',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='xpub',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
