# Generated by Django 2.1.7 on 2019-02-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0002_auto_20190217_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('quantity', models.FloatField()),
                ('title', models.TextField()),
                ('decription', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'products',
                'managed': True,
            },
        ),
    ]
