# Generated by Django 2.2.3 on 2019-07-10 18:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import gui.models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0002_auto_20190509_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bitcoin_address',
        ),
        migrations.RemoveField(
            model_name='product',
            name='bitcoin_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.CharField(default=gui.models.product_id, max_length=255, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=16)),
                ('status', models.CharField(default='active', max_length=1000)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('bitcoin_address', models.CharField(default='', max_length=255)),
                ('bitcoin_url', models.CharField(default='', max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.Product')),
            ],
            options={
                'db_table': 'invoices',
                'managed': True,
            },
        ),
    ]
