# Generated by Django 2.2.3 on 2019-07-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0003_auto_20190710_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='product',
        ),
        migrations.AddField(
            model_name='invoice',
            name='products',
            field=models.ManyToManyField(to='gui.Product'),
        ),
    ]
