# Generated by Django 2.1.7 on 2019-02-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0003_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
