# Generated by Django 2.1.7 on 2019-02-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0007_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='order_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
