# Generated by Django 2.1.7 on 2019-02-20 15:21

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0008_auto_20190220_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
