# Generated by Django 2.1.7 on 2019-02-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0009_product_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='can_delete',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
