# Generated by Django 2.1.7 on 2019-02-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0010_auto_20190222_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='website',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='xpub',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
