# Generated by Django 2.1.7 on 2019-02-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0012_auto_20190223_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='website',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='store',
            name='xpub',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
