# Generated by Django 2.1.7 on 2019-03-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0013_auto_20190223_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bitcoin_address',
            field=models.CharField(default='', max_length=255),
        ),
    ]
