name: Sync labels

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

permissions:
  issues: write

jobs:
  sync-labels:
    name: sync-labels
    runs-on: ubuntu-latest
    steps:
      - uses: EndBug/label-sync@v2
        with:
          config-file: "https://raw.githubusercontent.com/bitcart/.github/master/labels.yml"
          delete-other-labels: false
